-- Category-level decision provenance for every successfully evaluated POST and COMMENT request.
-- Raw post text, comment text, conversation context, author usernames, and OCR text are excluded.
-- The input SHA-256 is a length-framed envelope fingerprint and remains pseudonymous data; its
-- retention and access policy must be supplied by the deployment.

CREATE TABLE moderation_content_decision_audit_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    request_id VARCHAR(128) NOT NULL,
    content_id VARCHAR(128) NOT NULL,
    content_type VARCHAR(16) NOT NULL,
    moderation_path VARCHAR(32) NOT NULL,
    deciding_layer VARCHAR(32) NOT NULL,

    input_contract_version VARCHAR(64) NOT NULL,
    input_sha256 CHAR(64) NOT NULL,
    text_length INTEGER NOT NULL,
    parent_post_text_length INTEGER NOT NULL,
    parent_post_text_redacted BOOLEAN NOT NULL,
    author_username_length INTEGER NOT NULL,
    author_username_redacted BOOLEAN NOT NULL,
    quoted_text_length INTEGER NOT NULL,
    image_present BOOLEAN NOT NULL,
    image_sha256 CHAR(64),
    image_size_bytes BIGINT,
    image_content_type VARCHAR(32),

    final_decision VARCHAR(16) NOT NULL,
    violation VARCHAR(64) NOT NULL,
    final_reason VARCHAR(64) NOT NULL,
    domain VARCHAR(64),
    safety_action VARCHAR(16),
    safety VARCHAR(64),
    financial_claim VARCHAR(64),
    financial_risk VARCHAR(64),
    financial_privacy VARCHAR(16),
    impersonation VARCHAR(16),
    political_context VARCHAR(64),
    restricted_political_entity VARCHAR(64),
    local_policy_terminal BOOLEAN NOT NULL,
    local_policy_violation VARCHAR(64),
    local_restricted_political_entity VARCHAR(64),
    image_match VARCHAR(64),

    provenance_schema_version VARCHAR(64) NOT NULL,
    policy_version VARCHAR(64) NOT NULL,
    reducer_version VARCHAR(64) NOT NULL,
    moderation_score_block_threshold NUMERIC(18, 17) NOT NULL,
    blocked_terms_digest CHAR(64) NOT NULL,
    restricted_political_registry_digest CHAR(64) NOT NULL,
    financial_privacy_scanner_version VARCHAR(64) NOT NULL,
    financial_privacy_scanner_sha256 CHAR(64) NOT NULL,
    decision_configuration_version VARCHAR(64) NOT NULL,
    decision_configuration_digest CHAR(64) NOT NULL,
    decision_configuration_snapshot VARCHAR(4096) NOT NULL,

    verdict_source VARCHAR(16) NOT NULL,
    moderation_status VARCHAR(16) NOT NULL,
    actual_moderation_model VARCHAR(128) NOT NULL,
    classification_status VARCHAR(16) NOT NULL,
    actual_classification_model VARCHAR(128) NOT NULL,
    adjudication_status VARCHAR(16) NOT NULL,
    actual_adjudication_model VARCHAR(128) NOT NULL,
    configured_ai_provider VARCHAR(128) NOT NULL,
    configured_moderation_model VARCHAR(128) NOT NULL,
    configured_moderation_profile_sha256 VARCHAR(64) NOT NULL,
    configured_classification_model VARCHAR(128) NOT NULL,
    configured_classification_prompt_bundle_sha256 VARCHAR(64) NOT NULL,
    configured_classification_profile_sha256 VARCHAR(64) NOT NULL,
    configured_adjudication_model VARCHAR(128) NOT NULL,
    configured_adjudication_reasoning_effort VARCHAR(16) NOT NULL,
    configured_adjudication_prompt_version VARCHAR(64) NOT NULL,
    configured_adjudication_prompt_sha256 VARCHAR(64) NOT NULL,
    configured_adjudication_profile_sha256 VARCHAR(64) NOT NULL,
    configured_openai_timeout_seconds VARCHAR(16) NOT NULL,
    configured_max_image_bytes VARCHAR(16) NOT NULL,
    configured_max_image_request_bytes VARCHAR(16) NOT NULL,
    ai_configuration_status VARCHAR(16) NOT NULL,
    observed_ai_configuration_digest VARCHAR(64) NOT NULL,
    observed_ai_configuration_snapshot VARCHAR(2048) NOT NULL,

    ai_metered_calls INTEGER NOT NULL,
    ai_free_moderation_calls INTEGER NOT NULL,
    ai_input_tokens BIGINT NOT NULL,
    ai_cached_input_tokens BIGINT NOT NULL,
    ai_cache_write_tokens BIGINT NOT NULL,
    ai_output_tokens BIGINT NOT NULL,
    ai_reasoning_tokens BIGINT NOT NULL,
    ai_total_tokens BIGINT NOT NULL,
    ai_estimated_cost_usd NUMERIC(24, 12),
    ai_currency VARCHAR(8) NOT NULL,
    ai_pricing_version VARCHAR(64) NOT NULL,
    ai_usage_complete BOOLEAN NOT NULL,
    ai_cost_complete BOOLEAN NOT NULL,
    ai_model_calls JSONB NOT NULL,

    latency_ms INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT content_audit_request_nonblank CHECK (
        request_id ~ '^[A-Za-z0-9][A-Za-z0-9._:~-]{0,127}$'
    ),
    CONSTRAINT content_audit_content_nonblank CHECK (
        content_id ~ '^[A-Za-z0-9][A-Za-z0-9._:~-]{0,127}$'
    ),
    CONSTRAINT content_audit_type CHECK (content_type IN ('POST', 'COMMENT')),
    CONSTRAINT content_audit_path CHECK (
        moderation_path IN ('LOCAL_POLICY', 'TEXT_AI', 'IMAGE_PIPELINE')
    ),
    CONSTRAINT content_audit_layer CHECK (deciding_layer IN (
        'LOCAL_POLICY',
        'IMAGE_EXACT_MATCH',
        'PROVIDER_MODERATION',
        'CLASSIFIER',
        'ADJUDICATOR',
        'ANALYZER_UNAVAILABLE',
        'EVIDENCE_UNAVAILABLE'
    )),
    CONSTRAINT content_audit_input_contract CHECK (
        input_contract_version = 'moderation-input-envelope-v1'
    ),
    CONSTRAINT content_audit_input_sha CHECK (input_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT content_audit_lengths CHECK (
        text_length >= 0 AND text_length <= 20000
        AND parent_post_text_length >= 0 AND parent_post_text_length <= 20000
        AND author_username_length >= 0 AND author_username_length <= 128
        AND quoted_text_length >= 0 AND quoted_text_length <= 10000
    ),
    CONSTRAINT content_audit_image_binding CHECK (
        (image_present
            AND image_sha256 ~ '^[0-9a-f]{64}$'
            AND image_size_bytes > 0
            AND image_size_bytes <= 8388608
            AND image_content_type IN ('image/jpeg', 'image/png', 'image/gif')
            AND image_match IS NOT NULL
            AND moderation_path = 'IMAGE_PIPELINE')
        OR (NOT image_present
            AND image_sha256 IS NULL
            AND image_size_bytes IS NULL
            AND image_content_type IS NULL
            AND image_match IS NULL
            AND moderation_path <> 'IMAGE_PIPELINE')
    ),
    CONSTRAINT content_audit_local_path CHECK (
        image_present
        OR (local_policy_terminal AND moderation_path = 'LOCAL_POLICY')
        OR (NOT local_policy_terminal AND moderation_path = 'TEXT_AI')
    ),
    CONSTRAINT content_audit_final_decision CHECK (
        final_decision IN ('ALLOW', 'BLOCK', 'UNKNOWN')
    ),
    CONSTRAINT content_audit_violation CHECK (violation IN (
        'NONE', 'HARASSMENT', 'HATE', 'THREAT', 'SELF_HARM', 'SEXUAL',
        'SEXUAL_MINORS', 'GRAPHIC_VIOLENCE', 'VIOLENCE', 'ILLICIT',
        'SPAM_SCAM', 'VULGAR', 'IMPERSONATION', 'POLITICAL_CONTENT',
        'OFF_TOPIC', 'FINANCIAL_PRIVACY', 'FINANCIAL_RISK', 'NOT_INVESTMENT',
        'KNOWN_IMAGE', 'EVIDENCE_UNAVAILABLE', 'ANALYZER_ERROR', 'OTHER'
    )),
    CONSTRAINT content_audit_final_reason CHECK (final_reason IN (
        'NONE', 'KNOWN_IMAGE', 'SAFETY', 'FINANCIAL_PRIVACY',
        'FINANCIAL_RISK', 'IMPERSONATION', 'POLITICAL_CONTENT', 'OFF_TOPIC',
        'EVIDENCE_UNAVAILABLE', 'ANALYZER_ERROR'
    )),
    CONSTRAINT content_audit_outcome_binding CHECK (
        (final_decision = 'ALLOW' AND violation = 'NONE' AND final_reason = 'NONE')
        OR (final_decision <> 'ALLOW' AND violation <> 'NONE' AND final_reason <> 'NONE')
    ),
    CONSTRAINT content_audit_domain CHECK (
        domain IS NULL OR domain IN (
            'INVESTMENT_RELATED', 'INVESTMENT_ADJACENT', 'OFF_TOPIC', 'UNCERTAIN'
        )
    ),
    CONSTRAINT content_audit_safety_action CHECK (
        safety_action IS NULL OR safety_action IN ('ALLOW', 'BLOCK', 'UNKNOWN')
    ),
    CONSTRAINT content_audit_safety CHECK (
        safety IS NULL OR safety IN (
            'NONE', 'HARASSMENT', 'HATE', 'THREAT', 'SELF_HARM', 'SEXUAL',
            'SEXUAL_MINORS', 'GRAPHIC_VIOLENCE', 'VIOLENCE', 'ILLICIT',
            'SPAM_SCAM', 'VULGAR', 'OTHER'
        )
    ),
    CONSTRAINT content_audit_financial_claim CHECK (
        financial_claim IS NULL OR financial_claim IN (
            'NONE', 'OPINION', 'ANALYSIS', 'FACTUAL_CLAIM', 'UNCERTAIN'
        )
    ),
    CONSTRAINT content_audit_financial_risk CHECK (
        financial_risk IS NULL OR financial_risk IN (
            'NONE', 'POTENTIALLY_MISLEADING', 'GUARANTEED_RETURN',
            'INVESTMENT_SCAM', 'PUMP_AND_DUMP', 'MARKET_MANIPULATION',
            'PHISHING', 'PAID_PROMOTION', 'UNCERTAIN'
        )
    ),
    CONSTRAINT content_audit_financial_privacy CHECK (
        financial_privacy IS NULL OR financial_privacy IN ('NONE', 'POSSIBLE', 'CLEAR')
    ),
    CONSTRAINT content_audit_impersonation CHECK (
        impersonation IS NULL OR impersonation IN ('NONE', 'POSSIBLE', 'CLEAR')
    ),
    CONSTRAINT content_audit_political_context CHECK (
        political_context IS NULL OR political_context IN (
            'NONE', 'INVESTMENT_RELEVANT', 'GENERAL_POLITICS', 'UNCERTAIN'
        )
    ),
    CONSTRAINT content_audit_restricted_entity CHECK (
        restricted_political_entity IS NULL OR restricted_political_entity IN (
            'NONE', 'PRESIDENT', 'MINISTER', 'YAP', 'MULTIPLE', 'POSSIBLE'
        )
    ),
    CONSTRAINT content_audit_local_evidence CHECK (
        (local_policy_violation IS NULL OR local_policy_violation IN (
            'VULGAR', 'HATE', 'POLITICAL_CONTENT', 'OTHER'
        ))
        AND (local_restricted_political_entity IS NULL
            OR local_restricted_political_entity IN (
                'PRESIDENT', 'MINISTER', 'YAP', 'MULTIPLE', 'POSSIBLE'
            ))
    ),
    CONSTRAINT content_audit_image_match CHECK (
        image_match IS NULL OR image_match IN (
            'EXACT_MATCH', 'SIMILAR_CANDIDATE', 'MATCHED', 'NOT_MATCHED',
            'LOW_QUALITY', 'UNAVAILABLE'
        )
    ),
    CONSTRAINT content_audit_layer_evidence CHECK (
        local_policy_terminal = (deciding_layer = 'LOCAL_POLICY')
        AND (deciding_layer <> 'LOCAL_POLICY'
            OR local_policy_violation IS NOT NULL
            OR financial_privacy = 'CLEAR'
            OR local_restricted_political_entity IN (
                'PRESIDENT', 'MINISTER', 'YAP', 'MULTIPLE'
            ))
        AND (deciding_layer <> 'IMAGE_EXACT_MATCH'
            OR (image_present
                AND image_match = 'EXACT_MATCH'
                AND final_reason = 'KNOWN_IMAGE'))
        AND (deciding_layer <> 'ANALYZER_UNAVAILABLE'
            OR (final_decision = 'UNKNOWN'
                AND violation = 'ANALYZER_ERROR'
                AND final_reason = 'ANALYZER_ERROR'))
        AND (deciding_layer <> 'EVIDENCE_UNAVAILABLE'
            OR (final_decision = 'UNKNOWN'
                AND violation = 'EVIDENCE_UNAVAILABLE'
                AND final_reason = 'EVIDENCE_UNAVAILABLE'))
    ),
    CONSTRAINT content_audit_provenance CHECK (
        provenance_schema_version = 'content-decision-provenance-v1'
    ),
    CONSTRAINT content_audit_policy_values CHECK (
        btrim(policy_version) <> ''
        AND btrim(reducer_version) <> ''
        AND btrim(financial_privacy_scanner_version) <> ''
        AND decision_configuration_version = 'content-decision-config-v1'
        AND btrim(decision_configuration_snapshot) <> ''
    ),
    CONSTRAINT content_audit_threshold CHECK (
        moderation_score_block_threshold >= 0
        AND moderation_score_block_threshold <= 1
    ),
    CONSTRAINT content_audit_policy_digests CHECK (
        blocked_terms_digest ~ '^[0-9a-f]{64}$'
        AND restricted_political_registry_digest ~ '^[0-9a-f]{64}$'
        AND financial_privacy_scanner_sha256 ~ '^[0-9a-f]{64}$'
        AND decision_configuration_digest ~ '^[0-9a-f]{64}$'
    ),
    CONSTRAINT content_audit_verdict_source CHECK (
        verdict_source IN ('LIVE', 'CACHE', 'NOT_INVOKED')
    ),
    CONSTRAINT content_audit_statuses CHECK (
        moderation_status IN ('ok', 'error', 'not_required', 'unavailable')
        AND classification_status IN ('ok', 'error', 'not_required', 'unavailable')
        AND adjudication_status IN ('ok', 'error', 'not_required', 'unavailable')
    ),
    CONSTRAINT content_audit_actual_models CHECK (
        ((moderation_status = 'ok'
                AND actual_moderation_model NOT IN ('not_invoked', 'unavailable'))
            OR (moderation_status = 'not_required'
                AND actual_moderation_model = 'not_invoked')
            OR (moderation_status IN ('error', 'unavailable')
                AND actual_moderation_model = 'unavailable'))
        AND ((classification_status = 'ok'
                AND actual_classification_model NOT IN ('not_invoked', 'unavailable'))
            OR (classification_status = 'not_required'
                AND actual_classification_model = 'not_invoked')
            OR (classification_status IN ('error', 'unavailable')
                AND actual_classification_model = 'unavailable'))
        AND ((adjudication_status = 'ok'
                AND actual_adjudication_model NOT IN ('not_invoked', 'unavailable'))
            OR (adjudication_status = 'not_required'
                AND actual_adjudication_model = 'not_invoked')
            OR (adjudication_status IN ('error', 'unavailable')
                AND actual_adjudication_model = 'unavailable'))
    ),
    CONSTRAINT content_audit_reasoning_effort CHECK (
        configured_adjudication_reasoning_effort IN (
            'none', 'minimal', 'low', 'medium', 'high', 'xhigh',
            'not_invoked', 'unavailable'
        )
    ),
    CONSTRAINT content_audit_ai_config_status CHECK (
        ai_configuration_status IN ('matched', 'mismatch', 'unavailable', 'not_invoked')
    ),
    CONSTRAINT content_audit_not_invoked CHECK (
        ai_configuration_status <> 'not_invoked'
        OR (verdict_source = 'NOT_INVOKED'
            AND configured_ai_provider = 'not_invoked'
            AND configured_moderation_model = 'not_invoked'
            AND configured_moderation_profile_sha256 = 'not_invoked'
            AND configured_classification_model = 'not_invoked'
            AND configured_classification_prompt_bundle_sha256 = 'not_invoked'
            AND configured_classification_profile_sha256 = 'not_invoked'
            AND configured_adjudication_model = 'not_invoked'
            AND configured_adjudication_reasoning_effort = 'not_invoked'
            AND configured_adjudication_prompt_version = 'not_invoked'
            AND configured_adjudication_prompt_sha256 = 'not_invoked'
            AND configured_adjudication_profile_sha256 = 'not_invoked'
            AND configured_openai_timeout_seconds = 'not_invoked'
            AND configured_max_image_bytes = 'not_invoked'
            AND configured_max_image_request_bytes = 'not_invoked'
            AND observed_ai_configuration_digest = 'not_invoked'
            AND observed_ai_configuration_snapshot = 'not_invoked')
    ),
    CONSTRAINT content_audit_local_not_invoked CHECK (
        NOT local_policy_terminal
        OR (verdict_source = 'NOT_INVOKED'
            AND moderation_status = 'not_required'
            AND actual_moderation_model = 'not_invoked'
            AND classification_status = 'not_required'
            AND actual_classification_model = 'not_invoked'
            AND adjudication_status = 'not_required'
            AND actual_adjudication_model = 'not_invoked')
    ),
    CONSTRAINT content_audit_usage_nonnegative CHECK (
        ai_metered_calls >= 0 AND ai_metered_calls <= 3
        AND ai_free_moderation_calls >= 0 AND ai_free_moderation_calls <= 1
        AND ai_input_tokens >= 0
        AND ai_cached_input_tokens >= 0
        AND ai_cache_write_tokens >= 0
        AND ai_output_tokens >= 0
        AND ai_reasoning_tokens >= 0
        AND ai_total_tokens >= 0
        AND (ai_estimated_cost_usd IS NULL OR ai_estimated_cost_usd >= 0)
    ),
    CONSTRAINT content_audit_usage_subsets CHECK (
        ai_cached_input_tokens <= ai_input_tokens
        AND ai_cache_write_tokens <= ai_input_tokens - ai_cached_input_tokens
        AND ai_reasoning_tokens <= ai_output_tokens
        AND ai_total_tokens = ai_input_tokens + ai_output_tokens
        AND ai_model_calls @> '[]'::JSONB
        AND jsonb_typeof(ai_model_calls) = 'array'
        AND jsonb_array_length(ai_model_calls) = ai_metered_calls
    ),
    CONSTRAINT content_audit_cost_binding CHECK (
        ai_cost_complete = (ai_estimated_cost_usd IS NOT NULL)
        AND (ai_usage_complete OR NOT ai_cost_complete)
    ),
    CONSTRAINT content_audit_cached_usage CHECK (
        verdict_source NOT IN ('CACHE', 'NOT_INVOKED')
        OR (ai_metered_calls = 0
            AND ai_free_moderation_calls = 0
            AND ai_input_tokens = 0
            AND ai_cached_input_tokens = 0
            AND ai_cache_write_tokens = 0
            AND ai_output_tokens = 0
            AND ai_reasoning_tokens = 0
            AND ai_total_tokens = 0
            AND ai_model_calls = '[]'::JSONB)
    ),
    CONSTRAINT content_audit_currency CHECK (ai_currency = 'USD'),
    CONSTRAINT content_audit_latency CHECK (latency_ms >= 0 AND latency_ms <= 600000)
);

CREATE TABLE moderation_post_decision_audit_events (
    LIKE moderation_content_decision_audit_template
        INCLUDING DEFAULTS INCLUDING CONSTRAINTS INCLUDING IDENTITY INCLUDING STORAGE
);

CREATE TABLE moderation_comment_decision_audit_events (
    LIKE moderation_content_decision_audit_template
        INCLUDING DEFAULTS INCLUDING CONSTRAINTS INCLUDING IDENTITY INCLUDING STORAGE
);

DROP TABLE moderation_content_decision_audit_template;

ALTER TABLE moderation_post_decision_audit_events
    ADD PRIMARY KEY (id),
    ADD CONSTRAINT post_audit_category CHECK (content_type = 'POST'),
    ADD CONSTRAINT post_audit_input CHECK (
        (text_length > 0 OR image_present)
        AND parent_post_text_length = 0
        AND NOT parent_post_text_redacted
        AND author_username_length = 0
        AND NOT author_username_redacted
        AND quoted_text_length = 0
    );

ALTER TABLE moderation_comment_decision_audit_events
    ADD PRIMARY KEY (id),
    ADD CONSTRAINT comment_audit_category CHECK (content_type = 'COMMENT'),
    ADD CONSTRAINT comment_audit_input CHECK (
        text_length > 0
        AND NOT image_present
        AND (NOT parent_post_text_redacted OR parent_post_text_length > 0)
        AND (NOT author_username_redacted OR author_username_length > 0)
    );

CREATE INDEX post_audit_content_created_idx
    ON moderation_post_decision_audit_events (content_id, created_at DESC, id DESC);
CREATE INDEX post_audit_request_created_idx
    ON moderation_post_decision_audit_events (request_id, created_at DESC, id DESC);
CREATE INDEX post_audit_created_idx
    ON moderation_post_decision_audit_events (created_at DESC, id DESC);
CREATE INDEX post_audit_outcome_created_idx
    ON moderation_post_decision_audit_events (
        final_decision, violation, created_at DESC, id DESC
    );

CREATE INDEX comment_audit_content_created_idx
    ON moderation_comment_decision_audit_events (content_id, created_at DESC, id DESC);
CREATE INDEX comment_audit_request_created_idx
    ON moderation_comment_decision_audit_events (request_id, created_at DESC, id DESC);
CREATE INDEX comment_audit_created_idx
    ON moderation_comment_decision_audit_events (created_at DESC, id DESC);
CREATE INDEX comment_audit_outcome_created_idx
    ON moderation_comment_decision_audit_events (
        final_decision, violation, created_at DESC, id DESC
    );

CREATE FUNCTION reject_moderation_content_audit_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION '% audit events are append-only', TG_TABLE_NAME
        USING ERRCODE = '55000';
END;
$$;

CREATE TRIGGER post_audit_no_update_delete
BEFORE UPDATE OR DELETE ON moderation_post_decision_audit_events
FOR EACH ROW
EXECUTE FUNCTION reject_moderation_content_audit_mutation();

CREATE TRIGGER post_audit_no_truncate
BEFORE TRUNCATE ON moderation_post_decision_audit_events
FOR EACH STATEMENT
EXECUTE FUNCTION reject_moderation_content_audit_mutation();

CREATE TRIGGER comment_audit_no_update_delete
BEFORE UPDATE OR DELETE ON moderation_comment_decision_audit_events
FOR EACH ROW
EXECUTE FUNCTION reject_moderation_content_audit_mutation();

CREATE TRIGGER comment_audit_no_truncate
BEFORE TRUNCATE ON moderation_comment_decision_audit_events
FOR EACH STATEMENT
EXECUTE FUNCTION reject_moderation_content_audit_mutation();

COMMENT ON TABLE moderation_post_decision_audit_events IS
    'Append-only POST decision provenance. Raw content is excluded.';
COMMENT ON TABLE moderation_comment_decision_audit_events IS
    'Append-only COMMENT decision provenance. Raw content and author identity are excluded.';

-- A safe, common operational surface. Username handles and input fingerprints are intentionally
-- absent; reviewers can follow request_id/content_id under their deployment access policy.
CREATE VIEW moderation_decision_audit_summary AS
SELECT
    'POST'::VARCHAR(16) AS content_type,
    id,
    request_id,
    content_id,
    final_decision,
    violation,
    final_reason,
    deciding_layer,
    verdict_source,
    policy_version,
    latency_ms,
    created_at
FROM moderation_post_decision_audit_events
UNION ALL
SELECT
    'COMMENT'::VARCHAR(16),
    id,
    request_id,
    content_id,
    final_decision,
    violation,
    final_reason,
    deciding_layer,
    verdict_source,
    policy_version,
    latency_ms,
    created_at
FROM moderation_comment_decision_audit_events
UNION ALL
SELECT
    'USERNAME'::VARCHAR(16),
    id,
    request_id,
    content_id,
    final_decision,
    violation,
    final_reason,
    deciding_layer,
    verdict_source,
    policy_version,
    latency_ms,
    created_at
FROM moderation_username_decision_audit_events;
