package com.example.moderation.gateway.api;

public enum ErrorCode {
    INVALID_INPUT,
    NOT_FOUND,
    METHOD_NOT_ALLOWED,
    NOT_ACCEPTABLE,
    UNSUPPORTED_MEDIA_TYPE,
    PAYLOAD_TOO_LARGE,
    UNPROCESSABLE_IMAGE,
    UPSTREAM_FAILURE,
    SERVICE_UNAVAILABLE,
    UPSTREAM_TIMEOUT,
    INTERNAL_ERROR
}
